In [1]:
import pandas as pd

In [2]:
people = {
    "first" : ["Lalit", "Suraj", "Ankit", "Vikash", "Shohel"],
    "last" : ["Siraswa", "Dhadeech", "Verma", "Tawar", "Khan"],
    "email" : ["lalitsiraswa@gmail.com", "surajdhadeech@gmail.com", "ankitverma@gmail.com", "vikashtawar@gmail.com", "shohelkhan@gmail.com"]
}

In [3]:
df = pd.DataFrame(data = people)
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [4]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [5]:
df.columns = ["first_name", "last_name", "email"]

In [6]:
df

first_name last_name                    email
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [7]:
df.columns = [x.upper() for x in df.columns]

In [8]:
df

FIRST_NAME LAST_NAME                    EMAIL
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [9]:
df.columns

Index(['FIRST_NAME', 'LAST_NAME', 'EMAIL'], dtype='object')

In [10]:
df.columns = [x.lower() for x in df.columns]
df

first_name last_name                    email
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [11]:
df.columns = df.columns.str.replace("_", " ")
df

first name last name                    email
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [12]:
df.columns = [x.upper() for x in df.columns]
df

FIRST NAME LAST NAME                    EMAIL
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [13]:
df.columns = df.columns.str.replace(" ", "_")
df

FIRST_NAME LAST_NAME                    EMAIL
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [14]:
print(df.FIRST_NAME.head(2), "\n")
print(df.LAST_NAME.tail(2), "\n")
print(df.EMAIL.head(2), "\n")

0    Lalit
1    Suraj
Name: FIRST_NAME, dtype: object 

3    Tawar
4     Khan
Name: LAST_NAME, dtype: object 

0     lalitsiraswa@gmail.com
1    surajdhadeech@gmail.com
Name: EMAIL, dtype: object 



In [15]:
df.columns = [x.lower() for x in df.columns]
df

first_name last_name                    email
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [16]:
df.rename(columns = {"first_name" : "first", "last_name" : "last"}, inplace = True)
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [17]:
df.rename(columns = {"first" : "first_name", "last" : "last_name"}, inplace = True)
df

first_name last_name                    email
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com

In [18]:
df.rename(columns = {"first_name" : "first", "last_name" : "last"}, inplace = True)
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [19]:
print(df.loc[1, "last"], "\n")
df.loc[1, "last"] = "Sharma"
print(df.loc[1, "last"], "\n")

Dhadeech 

Sharma 



In [20]:
df.loc[1] = ["Suraj", "Dhadeech", "surajdhadeech@gmail.com"]
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [21]:
df.loc[1, ["last", "email"]] = ["Siraswa", "surajsiraswa@gmail.com"]
df

first     last                   email
0   Lalit  Siraswa  lalitsiraswa@gmail.com
1   Suraj  Siraswa  surajsiraswa@gmail.com
2   Ankit    Verma    ankitverma@gmail.com
3  Vikash    Tawar   vikashtawar@gmail.com
4  Shohel     Khan    shohelkhan@gmail.com

In [22]:
df.loc[2, ["last", "email"]] = ["Kumawat", "vermaankit@gmail.com"]
df

first     last                   email
0   Lalit  Siraswa  lalitsiraswa@gmail.com
1   Suraj  Siraswa  surajsiraswa@gmail.com
2   Ankit  Kumawat    vermaankit@gmail.com
3  Vikash    Tawar   vikashtawar@gmail.com
4  Shohel     Khan    shohelkhan@gmail.com

In [23]:
df.loc[0, ["last", "email"]] = ['Kumawat', "lalitkumawat@gmail.com"]
df

first     last                   email
0   Lalit  Kumawat  lalitkumawat@gmail.com
1   Suraj  Siraswa  surajsiraswa@gmail.com
2   Ankit  Kumawat    vermaankit@gmail.com
3  Vikash    Tawar   vikashtawar@gmail.com
4  Shohel     Khan    shohelkhan@gmail.com

In [24]:
df.loc[0, ["last", "email"]] = ["Siraswa", "lalitsiraswa@gmail.com"]
df.loc[1, ["last", "email"]] = ["Dhadeech", "dhadeechsuraj@gmail.com"]
df.loc[2, ["last", "email"]] = ["Verma", "vermaankit@gmail.com"]
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [25]:
df.at[0, ["last", "email"]] = ["Kumawat", "kumawatlalit@gmail.com"]
df

first      last                    email
0   Lalit   Kumawat   kumawatlalit@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [26]:
df.at[2, ["last", "email"]] = ["Kumawat", "kumawatankit@gmail.com"]
df

first      last                    email
0   Lalit   Kumawat   kumawatlalit@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit   Kumawat   kumawatankit@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [27]:
df.at[3, ["last", "email"]] = ["Tanwar", "vikashtanwar@gmail.com"]
df.at[0, ["last", "email"]] = ["Siraswa", "lalitsiraswa@gmail.com"]
df.at[2, ["last", "email"]] = ["Verma", "vermaankit@gmail.com"]
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash    Tanwar   vikashtanwar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [28]:
filt = (df["last"] == "Siraswa")
print(df[filt], "\n")
print(df.loc[filt], "\n")
print(df.loc[filt, "last"], "\n")
print(df.loc[filt]["last"], "\n")
print(df[filt]["first"], "\n")
df.loc[filt, "first"] = "Lucky"
# df.loc[filt]["first"] = "Lalit"
df.loc[filt, "first"] = "Lalit"
df

   first     last                   email
0  Lalit  Siraswa  lalitsiraswa@gmail.com 

   first     last                   email
0  Lalit  Siraswa  lalitsiraswa@gmail.com 

0    Siraswa
Name: last, dtype: object 

0    Siraswa
Name: last, dtype: object 

0    Lalit
Name: first, dtype: object 



first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash    Tanwar   vikashtanwar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [29]:
print(df)

    first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash    Tanwar   vikashtanwar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com


In [30]:
df.loc[2]["last"] = "Sharma"
filt = df["last"] == "Sharma"
df[filt] ["last"] = "Verma"
df.loc[filt]["last"] = "Verma"
df.loc[filt, "last"] = "Verma"
df

C:\Users\DeViL-AnGeL\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\DeViL-AnGeL\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash    Tanwar   vikashtanwar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [31]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash    Tanwar   vikashtanwar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [32]:
df.at[0 : , "last"] = ["Kumawat", "Sharma", "Verma", "Tanvar", "Khan"]
df

first     last                    email
0   Lalit  Kumawat   lalitsiraswa@gmail.com
1   Suraj   Sharma  dhadeechsuraj@gmail.com
2   Ankit    Verma     vermaankit@gmail.com
3  Vikash   Tanvar   vikashtanwar@gmail.com
4  Shohel     Khan     shohelkhan@gmail.com

In [33]:
df.loc[0 : , "last"] = ["Siraswa", "Dhadeech", "Verma", "Tanwar", "Khan"]
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  dhadeechsuraj@gmail.com
2   Ankit     Verma     vermaankit@gmail.com
3  Vikash    Tanwar   vikashtanwar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [34]:
df["email"] = [x.upper() for x in df["email"]]
df

first      last                    email
0   Lalit   Siraswa   LALITSIRASWA@GMAIL.COM
1   Suraj  Dhadeech  DHADEECHSURAJ@GMAIL.COM
2   Ankit     Verma     VERMAANKIT@GMAIL.COM
3  Vikash    Tanwar   VIKASHTANWAR@GMAIL.COM
4  Shohel      Khan     SHOHELKHAN@GMAIL.COM

In [35]:
print(df["first"].str.upper(), "\n")
print(df["last"].str.lower(), "\n")
print(df["first"].str.title(), "\n")
print(df["last"].str.capitalize(), "\n")

0     LALIT
1     SURAJ
2     ANKIT
3    VIKASH
4    SHOHEL
Name: first, dtype: object 

0     siraswa
1    dhadeech
2       verma
3      tanwar
4        khan
Name: last, dtype: object 

0     Lalit
1     Suraj
2     Ankit
3    Vikash
4    Shohel
Name: first, dtype: object 

0     Siraswa
1    Dhadeech
2       Verma
3      Tanwar
4        Khan
Name: last, dtype: object 



In [36]:
print(df, "\n")
df.loc["email"] = df["email"].str.lower()
print(df, "\n")

    first      last                    email
0   Lalit   Siraswa   LALITSIRASWA@GMAIL.COM
1   Suraj  Dhadeech  DHADEECHSURAJ@GMAIL.COM
2   Ankit     Verma     VERMAANKIT@GMAIL.COM
3  Vikash    Tanwar   VIKASHTANWAR@GMAIL.COM
4  Shohel      Khan     SHOHELKHAN@GMAIL.COM 

        first      last                    email
0       Lalit   Siraswa   LALITSIRASWA@GMAIL.COM
1       Suraj  Dhadeech  DHADEECHSURAJ@GMAIL.COM
2       Ankit     Verma     VERMAANKIT@GMAIL.COM
3      Vikash    Tanwar   VIKASHTANWAR@GMAIL.COM
4      Shohel      Khan     SHOHELKHAN@GMAIL.COM
email     NaN       NaN                      NaN 



In [37]:
df["email"] = df["email"].str.upper()

In [38]:
def update_email(email):
    return str(email).upper()

In [39]:
df["email"].apply(update_email)

0         LALITSIRASWA@GMAIL.COM
1        DHADEECHSURAJ@GMAIL.COM
2           VERMAANKIT@GMAIL.COM
3         VIKASHTANWAR@GMAIL.COM
4           SHOHELKHAN@GMAIL.COM
email                        NAN
Name: email, dtype: object

In [40]:
df

first      last                    email
0       Lalit   Siraswa   LALITSIRASWA@GMAIL.COM
1       Suraj  Dhadeech  DHADEECHSURAJ@GMAIL.COM
2       Ankit     Verma     VERMAANKIT@GMAIL.COM
3      Vikash    Tanwar   VIKASHTANWAR@GMAIL.COM
4      Shohel      Khan     SHOHELKHAN@GMAIL.COM
email     NaN       NaN                      NaN

In [41]:
people = {
    "first" : ["Lalit", "Suraj", "Ankit", "Vikash", "Shohel"],
    "last" : ["Siraswa", "Dhadeech", "Verma", "Tawar", "Khan"],
    "email" : ["lalitsiraswa@gmail.com", "surajdhadeech@gmail.com", "ankitverma@gmail.com", "vikashtawar@gmail.com", "shohelkhan@gmail.com"]
}

In [42]:
df = pd.DataFrame(data = people)
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [43]:
print(df["email"].str.upper(), "\n")
print(df["email"].str.title(), "\n")
print(df["email"].str.capitalize(), "\n")

0     LALITSIRASWA@GMAIL.COM
1    SURAJDHADEECH@GMAIL.COM
2       ANKITVERMA@GMAIL.COM
3      VIKASHTAWAR@GMAIL.COM
4       SHOHELKHAN@GMAIL.COM
Name: email, dtype: object 

0     Lalitsiraswa@Gmail.Com
1    Surajdhadeech@Gmail.Com
2       Ankitverma@Gmail.Com
3      Vikashtawar@Gmail.Com
4       Shohelkhan@Gmail.Com
Name: email, dtype: object 

0     Lalitsiraswa@gmail.com
1    Surajdhadeech@gmail.com
2       Ankitverma@gmail.com
3      Vikashtawar@gmail.com
4       Shohelkhan@gmail.com
Name: email, dtype: object 



In [44]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [45]:
# print(df["first"].apply(lambda name : name.upper()), "\n")
# print(df["last"].apply(lambda lastname : lastname.lower()), "\n")
# print(df["last"].apply(lambda lastname : lastname.title()), "\n")
# print(df["email"].apply(lambda email : email.upper()), "\n")

In [46]:
# print(df.sort_values("first"), "\n")
# print(df.sort_values("last"), "\n")

In [47]:
print(df["first"].max(), "\n")
print(df["first"].min(), "\n")

Vikash 

Ankit 



In [48]:
print(df.apply(len), "\n")
print(df.apply(len, axis = 1), "\n")

first    5
last     5
email    5
dtype: int64 

0    3
1    3
2    3
3    3
4    3
dtype: int64 



In [49]:
print(df.apply(pd.Series.min), "\n")
print(df.apply(pd.Series.max), "\n")

first                   Ankit
last                 Dhadeech
email    ankitverma@gmail.com
dtype: object 

first                   Vikash
last                     Verma
email    vikashtawar@gmail.com
dtype: object 



In [50]:
print(df.apply(lambda x : x.min()), "\n")
print(df.apply(lambda x : x.max()), "\n")

first                   Ankit
last                 Dhadeech
email    ankitverma@gmail.com
dtype: object 

first                   Vikash
last                     Verma
email    vikashtawar@gmail.com
dtype: object 



In [51]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [52]:
# applymap()
df.applymap(len)

first  last  email
0      5     7     22
1      5     8     23
2      5     5     20
3      6     5     21
4      6     4     20

In [53]:
# df["first"].apply(len)
# df.apply(len)

In [54]:
print(df.applymap(max), "\n")

  first last email
0     t    w     w
1     u    h     u
2     t    r     v
3     s    w     w
4     o    n     s 



In [55]:
# df["first"].applymap(len)

In [56]:
df.applymap(str.lower)

first      last                    email
0   lalit   siraswa   lalitsiraswa@gmail.com
1   suraj  dhadeech  surajdhadeech@gmail.com
2   ankit     verma     ankitverma@gmail.com
3  vikash     tawar    vikashtawar@gmail.com
4  shohel      khan     shohelkhan@gmail.com

In [57]:
df["first"].apply(str.title)
df["last"].apply(str.title)
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [58]:
#map
df["first"].map({"Lalit" : "Suraj", "Suraj" : "Lalit", "Ankit" : "Vikash", "Vikash" : "Shohel"})

0     Suraj
1     Lalit
2    Vikash
3    Shohel
4       NaN
Name: first, dtype: object

In [59]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [60]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [61]:
df.columns = ["first_name", "last_name", "email_id"]
print(df.columns, "\n")
print(df.columns[0], "\n")
print(df.columns[1], "\n")
print(df.columns[2], "\n")
# print(df.columns[3], "\n")

Index(['first_name', 'last_name', 'email_id'], dtype='object') 

first_name 

last_name 

email_id 



In [62]:
print(df, "\n")
print(df.apply(len), "\n")
print(df["first_name"].apply(len), "\n")
print(df.applymap(len), "\n")

  first_name last_name                 email_id
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com 

first_name    5
last_name     5
email_id      5
dtype: int64 

0    5
1    5
2    5
3    6
4    6
Name: first_name, dtype: int64 

   first_name  last_name  email_id
0           5          7        22
1           5          8        23
2           5          5        20
3           6          5        21
4           6          4        20 



In [63]:
print(df, "\n")

  first_name last_name                 email_id
0      Lalit   Siraswa   lalitsiraswa@gmail.com
1      Suraj  Dhadeech  surajdhadeech@gmail.com
2      Ankit     Verma     ankitverma@gmail.com
3     Vikash     Tawar    vikashtawar@gmail.com
4     Shohel      Khan     shohelkhan@gmail.com 



In [64]:
df.rename(columns = {"first_name" : "first", "last_name" : "last", "email_id" : "email"}, inplace = True)

In [65]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [66]:
people = {
    "first" : ["Lalit", "Suraj", "Ankit", "Vikash", "Shohel"],
    "last" : ["Siraswa", "Dhadeech", "Verma", "Tawar", "Khan"],
    "email" : ["lalitsiraswa@gmail.com", "surajdhadeech@gmail.com", "ankitverma@gmail.com", "vikashtawar@gmail.com", "shohelkhan@gmail.com"]
}

In [67]:
df = pd.DataFrame(data = people)
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [68]:
df["first"].map({"Lalit" : "lucky", "Suraj" : "Sonu", "Ankit" : "Bunty"})

0    lucky
1     Sonu
2    Bunty
3      NaN
4      NaN
Name: first, dtype: object

In [69]:
df["first"].replace({"Lalit" : "Lucky", "Suraj" : "Sonu", "Ankit" : "Bunty"})

0     Lucky
1      Sonu
2     Bunty
3    Vikash
4    Shohel
Name: first, dtype: object

In [70]:
df

first      last                    email
0   Lalit   Siraswa   lalitsiraswa@gmail.com
1   Suraj  Dhadeech  surajdhadeech@gmail.com
2   Ankit     Verma     ankitverma@gmail.com
3  Vikash     Tawar    vikashtawar@gmail.com
4  Shohel      Khan     shohelkhan@gmail.com

In [102]:
import numpy as np
array = np.arange(10, 210, 10).reshape(5, 4)
array

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [112]:
array[[0, 1, 2, 3, 4], [0, 1, 2, 3, 3]]

array([ 10,  60, 110, 160, 200])

In [116]:
array[[0, 2, 4], 0 : 4]

array([[ 10,  20,  30,  40],
       [ 90, 100, 110, 120],
       [170, 180, 190, 200]])

In [119]:
array[[0, 1, 2, 3], [0, 1, 2, 3]]

array([ 10,  60, 110, 160])

In [120]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
x[[[0, 0]], [[0, 2]]]

array([[0, 2]])

In [122]:
x[[[0, 0], [1, 1], [2, 2], [3, 3]], [[0, 2], [0, 2], [0, 2], [0, 2]]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])