In [1]:
import numpy as np
import pandas as pd

In [2]:
A = ["A", "B", "C", "D"]
B = ["E", "F", "G", "H"]
C = ["I", "J", "K", "L"]
D = ["M", "N", "O", "P"]
E = ["Q", "R", "S", "T"]
F = ["U", "V", "W", "X"]

In [13]:
df = pd.DataFrame(data = [A, B, C, D, E, F], index = ["A", "B", "C", "D", "E", "F"], columns = ['a', 'b', 'c', 'd'])
df["e"] = df["a"] + df["b"]
df["f"] = df["c"] + df["d"]
df

a  b  c  d   e   f
A  A  B  C  D  AB  CD
B  E  F  G  H  EF  GH
C  I  J  K  L  IJ  KL
D  M  N  O  P  MN  OP
E  Q  R  S  T  QR  ST
F  U  V  W  X  UV  WX

In [33]:
a = np.arange(0, 120, 10).reshape(4, 3)
print(a)
print(a[a > 70])
print([a > 70])
print(a == 0)
print(a != 100)

[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]
[ 80  90 100 110]
[array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True]])]
[[ True False False]
 [False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]]


In [34]:
A = [0, 1, 2, 3]
B = [4, 5, 6, 7]
C = [8, 9, 0, 1]
D = [2, 3, 4, 5]
E = [6, 7, 8, 9]
F = [0, 1, 2, 3]

df = pd.DataFrame(data = [A, B, C, D, E, F], index = ['A', 'B', 'C', 'D', 'E', 'F'], columns = ['a', 'b', 'c', 'd'])
df['e'] = df["a"] + df["b"]
df["f"] = df["c"] + df["d"]
df

a  b  c  d   e   f
A  0  1  2  3   1   5
B  4  5  6  7   9  13
C  8  9  0  1  17   1
D  2  3  4  5   5   9
E  6  7  8  9  13  17
F  0  1  2  3   1   5

In [41]:
print(df > 10)
print(df[df > 10])

       a      b      c      d      e      f
A  False  False  False  False  False  False
B  False  False  False  False  False   True
C  False  False  False  False   True  False
D  False  False  False  False  False  False
E  False  False  False  False   True   True
F  False  False  False  False  False  False
    a   b   c   d     e     f
A NaN NaN NaN NaN   NaN   NaN
B NaN NaN NaN NaN   NaN  13.0
C NaN NaN NaN NaN  17.0   NaN
D NaN NaN NaN NaN   NaN   NaN
E NaN NaN NaN NaN  13.0  17.0
F NaN NaN NaN NaN   NaN   NaN


In [54]:
print(df)
print(df["b"] > 3, end = "\n\n")
print(df["d"] > 8)

   a  b  c  d   e   f
A  0  1  2  3   1   5
B  4  5  6  7   9  13
C  8  9  0  1  17   1
D  2  3  4  5   5   9
E  6  7  8  9  13  17
F  0  1  2  3   1   5
A    False
B     True
C     True
D    False
E     True
F    False
Name: b, dtype: bool

A    False
B    False
C    False
D    False
E     True
F    False
Name: d, dtype: bool


In [55]:
print(df)

   a  b  c  d   e   f
A  0  1  2  3   1   5
B  4  5  6  7   9  13
C  8  9  0  1  17   1
D  2  3  4  5   5   9
E  6  7  8  9  13  17
F  0  1  2  3   1   5


In [68]:
print(df[df["f"] > 8], "\n")
print(df[df["f"] > 8]["f"], end = "\n")
print(df["e"] > 5, end = "\n")
print(df[df["e"] > 5], end = "\n\n")
print(df[df["e"] > 5]["e"], end = "\n")
print(df[df["e"] > 5][["e", "f"]], end = "\n")

   a  b  c  d   e   f
B  4  5  6  7   9  13
D  2  3  4  5   5   9
E  6  7  8  9  13  17 

B    13
D     9
E    17
Name: f, dtype: int64
A    False
B     True
C     True
D    False
E     True
F    False
Name: e, dtype: bool
   a  b  c  d   e   f
B  4  5  6  7   9  13
C  8  9  0  1  17   1
E  6  7  8  9  13  17

B     9
C    17
E    13
Name: e, dtype: int64
    e   f
B   9  13
C  17   1
E  13  17


In [70]:
print(df)

   a  b  c  d   e   f
A  0  1  2  3   1   5
B  4  5  6  7   9  13
C  8  9  0  1  17   1
D  2  3  4  5   5   9
E  6  7  8  9  13  17
F  0  1  2  3   1   5


In [90]:
print(df[df > 10][["e", "f"]], "\n")
print(df[df["f"] < 10]["f"], "\n")

      e     f
A   NaN   NaN
B   NaN  13.0
C  17.0   NaN
D   NaN   NaN
E  13.0  17.0
F   NaN   NaN 

A    5
C    1
D    9
F    5
Name: f, dtype: int64 



In [112]:
print(df)
print(df[(df > 5) & (df < 10)])
print((df["f"] > 5) & (df["f"] < 10), end = "\n")
print(df[(df["f"] > 5) & (df["f"] < 10)], end = "\n\n")
print(df[(df["f"] > 5) & (df["f"] < 10)]["f"], end = "\n")

   a  b  c  d   e   f
A  0  1  2  3   1   5
B  4  5  6  7   9  13
C  8  9  0  1  17   1
D  2  3  4  5   5   9
E  6  7  8  9  13  17
F  0  1  2  3   1   5
     a    b    c    d    e    f
A  NaN  NaN  NaN  NaN  NaN  NaN
B  NaN  NaN  6.0  7.0  9.0  NaN
C  8.0  9.0  NaN  NaN  NaN  NaN
D  NaN  NaN  NaN  NaN  NaN  9.0
E  6.0  7.0  8.0  9.0  NaN  NaN
F  NaN  NaN  NaN  NaN  NaN  NaN
A    False
B    False
C    False
D     True
E    False
F    False
Name: f, dtype: bool
   a  b  c  d  e  f
D  2  3  4  5  5  9

D    9
Name: f, dtype: int64


In [113]:
print(df)

   a  b  c  d   e   f
A  0  1  2  3   1   5
B  4  5  6  7   9  13
C  8  9  0  1  17   1
D  2  3  4  5   5   9
E  6  7  8  9  13  17
F  0  1  2  3   1   5


In [122]:
print((df["d"] > 5) & (df["f"] > 5), end = "\n")
print(df[(df["d"] > 5) & (df["f"] > 5)][["d", "f"]], end = "\n")

A    False
B     True
C    False
D    False
E     True
F    False
dtype: bool
   d   f
B  7  13
E  9  17
