In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'a' : [10, 5, 2, 4, 8], 'b' : [40, 20, 30, np.nan, 50]})
df

a     b
0  10  40.0
1   5  20.0
2   2  30.0
3   4   NaN
4   8  50.0

In [4]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=5, step=1)
Index(['a', 'b'], dtype='object')


In [5]:
print(df["a"].mean())
print(df["b"].mean())

5.8
35.0


In [6]:
df.describe().transpose()

count  mean        std   min   25%   50%   75%   max
a    5.0   5.8   3.193744   2.0   4.0   5.0   8.0  10.0
b    4.0  35.0  12.909944  20.0  27.5  35.0  42.5  50.0

In [7]:
df

a     b
0  10  40.0
1   5  20.0
2   2  30.0
3   4   NaN
4   8  50.0

In [8]:
def fun(x):
    x = x + 200
    return x

print(df.apply(fun))
print(df["b"].apply(fun))

     a      b
0  210  240.0
1  205  220.0
2  202  230.0
3  204    NaN
4  208  250.0
0    240.0
1    220.0
2    230.0
3      NaN
4    250.0
Name: b, dtype: float64


In [9]:
df["b"].sort_values()

1    20.0
2    30.0
0    40.0
4    50.0
3     NaN
Name: b, dtype: float64

In [10]:
print(df.sort_values("a"), "\n")
print(df.sort_values("b"))

    a     b
2   2  30.0
3   4   NaN
1   5  20.0
4   8  50.0
0  10  40.0 

    a     b
1   5  20.0
2   2  30.0
0  10  40.0
4   8  50.0
3   4   NaN


In [11]:
print(df["b"].unique())
print(df["a"].unique())

[40. 20. 30. nan 50.]
[10  5  2  4  8]


In [12]:
print(df["a"].nunique())
print(df["b"].nunique())

5
4


In [13]:
print(df["a"].value_counts(), "\n")
print(df["b"].value_counts())

5     1
4     1
2     1
10    1
8     1
Name: a, dtype: int64 

50.0    1
30.0    1
20.0    1
40.0    1
Name: b, dtype: int64


In [14]:
df.isnull()

a      b
0  False  False
1  False  False
2  False  False
3  False   True
4  False  False

In [15]:
df = pd.DataFrame(data = {'A' : [5, 6, 3, 2, 1], 'B' : [10, 9, 8, 7, 6], 'C' : [7, 3, 4, 8, 2]}, index = [2, 4, 6, 8, 10])
df

A   B  C
2   5  10  7
4   6   9  3
6   3   8  4
8   2   7  8
10  1   6  2

In [16]:
print(df.index)
print(df.columns)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
Index(['A', 'B', 'C'], dtype='object')


In [17]:
df["D"] = df["A"] + df["C"] 
df

A   B  C   D
2   5  10  7  12
4   6   9  3   9
6   3   8  4   7
8   2   7  8  10
10  1   6  2   3

In [18]:
print(df["D"].mean())
print(df["C"].min())
print(df["B"].max())
print(df.describe().transpose())

8.2
2
10
   count  mean       std  min  25%  50%   75%   max
A    5.0   3.4  2.073644  1.0  2.0  3.0   5.0   6.0
B    5.0   8.0  1.581139  6.0  7.0  8.0   9.0  10.0
C    5.0   4.8  2.588436  2.0  3.0  4.0   7.0   8.0
D    5.0   8.2  3.420526  3.0  7.0  9.0  10.0  12.0


In [19]:
def fun(x):
    x = x + 10
    return x
df["B"].apply(fun)

2     20
4     19
6     18
8     17
10    16
Name: B, dtype: int64

In [20]:
def fun(x):
    x = 10 - x
    return x
df['A'].apply(fun)

2     5
4     4
6     7
8     8
10    9
Name: A, dtype: int64

In [21]:
print(df)

    A   B  C   D
2   5  10  7  12
4   6   9  3   9
6   3   8  4   7
8   2   7  8  10
10  1   6  2   3


In [22]:
print(df["B"].sort_values(), "\n")
print(df.sort_values('C'), "\n")
print(df.sort_values("D"), "\n")
print(df["A"].sort_values(), "\n")

10     6
8      7
6      8
4      9
2     10
Name: B, dtype: int64 

    A   B  C   D
10  1   6  2   3
4   6   9  3   9
6   3   8  4   7
2   5  10  7  12
8   2   7  8  10 

    A   B  C   D
10  1   6  2   3
6   3   8  4   7
4   6   9  3   9
8   2   7  8  10
2   5  10  7  12 

10    1
8     2
6     3
2     5
4     6
Name: A, dtype: int64 



In [23]:
print(df, "\n")
print(df["A"].unique())
print(df["B"].unique())
print(df["C"].unique())
print(df["D"].unique())

    A   B  C   D
2   5  10  7  12
4   6   9  3   9
6   3   8  4   7
8   2   7  8  10
10  1   6  2   3 

[5 6 3 2 1]
[10  9  8  7  6]
[7 3 4 8 2]
[12  9  7 10  3]


In [24]:
print(df, "\n")
print(df["A"].nunique())
print(df["B"].nunique())
print(df["C"].nunique())
print(df["D"].nunique())

    A   B  C   D
2   5  10  7  12
4   6   9  3   9
6   3   8  4   7
8   2   7  8  10
10  1   6  2   3 

5
5
5
5


In [25]:
df = pd.DataFrame(data = {'A' : [5, 6, np.nan, 2, 1], 'B' : [np.nan, 9, 8, 7, 6], 'C' : [7, 3, 4, np.nan, 2]}, index = [2, 4, 6, 8, 10])
print(df, "\n")
print(df.isnull(), "\n")
print(df["A"].isnull(), "\n")
print(df["B"].isnull(), "\n")
print(df["C"].isnull(), "\n")

      A    B    C
2   5.0  NaN  7.0
4   6.0  9.0  3.0
6   NaN  8.0  4.0
8   2.0  7.0  NaN
10  1.0  6.0  2.0 

        A      B      C
2   False   True  False
4   False  False  False
6    True  False  False
8   False  False   True
10  False  False  False 

2     False
4     False
6      True
8     False
10    False
Name: A, dtype: bool 

2      True
4     False
6     False
8     False
10    False
Name: B, dtype: bool 

2     False
4     False
6     False
8      True
10    False
Name: C, dtype: bool 

